### PR TITLE
Minor update for Nim 2.0 (`db_connector` moved out of stdlib)

### PR DESCRIPTION
**Pull request by Yu-Vitaqua-fer-Chronos**
Changes:
  - Added [db_connector](https://github.com/nim-lang/db_connector) as a library (since this was the module stdlib pushed out)
  - Added a dependency on Nim 1.7.3+ (`db_connector` does this, so I thought it would make sense to do the same)
  - Changed the include from `db_postgres` to `db_connector/db_postgres` as that is the correct path

### CODE REVIEW

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Bumped the version since... It's self-explanatory aha (the library with these changes successfully build on my machine, too)

**Comment by treeform** [comment]
Ok but we need to figure out how to not break it for people?

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Sorry, forgot to reply to this a while ago, but I believe this should work now as it checks the Nim version and then decides if it should import db connector or not

**Comment by treeform** [comment]
Thank you for the PR, just run into this myself!

**Pull request merged**
